# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    goutte_client:
        class: "Goutte\Client"

    app.service.search_manager:
        class: AppBundle\Service\SearchManager

    app.service.search_engine.kilobaitas.parser:
        class: AppBundle\Service\SearchEngine\KilobaitasSearch\KilobaitasParser

    app.service.search_engine.kilobaitas.search:
        class: AppBundle\Service\SearchEngine\KilobaitasSearch\KilobaitasSearch
        arguments: ["@goutte_client", "@app.service.search_engine.kilobaitas.parser"]

    app.service.search_engine.skytech.parser:
        class: AppBundle\Service\SearchEngine\SkytechSearch\SkytechParser

    app.service.search_engine.skytech.search:
        class: AppBundle\Service\SearchEngine\SkytechSearch\SkytechSearch
        arguments: ["@goutte_client", "@app.service.search_engine.skytech.parser"]